# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBreak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingBreakExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeats', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('series', models.DecimalField(decimal_places=0, max_digits=2, null=True)),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitlife.Exercise')),
                ('training_break', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitlife.TrainingBreak')),
            ],
        ),
    ]
