# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlife', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
