# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitlife', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typical', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='products',
            name='type',
        ),
        migrations.AddField(
            model_name='products',
            name='typical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fitlife.Types'),
        ),
    ]
