# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitlife', '0003_auto_20170531_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='sex',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
